// Author: Fahadbin Alam (fma52), 4/23/26
// Mod by Codex, 4/23/26
// From One World Relief project content board data, 4/23/26
window.ONE_WORLD_RELIEF_PROJECTS = [
  {
    title: "Keeping a Hafiz Student in School",
    donationLabel: "Hafiz Student Support",
    acceptsDonations: true,
    category: "Orphan Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 001",
    amountRaised: "$600",
    verifiedOrphanBeneficiaries: 1,
    impact: "Financial support for a young Hafiz student after the loss of his father",
    summary: "One World Relief provided $600 in direct support for a young orphan continuing his Hafiz studies. The case documentation includes field photos and video proof from the delivery.",
    update: "Case media was organized into a donor-facing detail page on May 5, 2026.",
    thumbnailUrl: "assets/projects/case-001/orphan-support-001-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-001.html",
    donationUrl: "donate.html?program=orphan_annual&amount=300&referrer=case-001#donationForm"
  },
  {
    title: "A Fresh Start for a Father's Business",
    donationLabel: "Father's Business Support",
    acceptsDonations: true,
    category: "Livelihood Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 002",
    amountRaised: "$600",
    impact: "Direct livelihood support for a father rebuilding a small vegetable business",
    summary: "One World Relief provided $600 in financial support so a father of two could restart his vegetable business and support food, education, and daily needs for his family.",
    update: "Case media was organized into a donor-facing detail page on May 10, 2026.",
    thumbnailUrl: "assets/projects/case-002/livelihood-support-002-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-002.html",
    donationUrl: "donate.html?program=family_recovery&amount=600&referrer=case-002#donationForm"
  },
  {
    title: "Keeping an Orphan Boy in School",
    donationLabel: "Orphan Education",
    acceptsDonations: true,
    category: "Orphan Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 003",
    amountRaised: "$400",
    verifiedOrphanBeneficiaries: 1,
    impact: "Education support delivered for an orphan boy",
    summary: "One World Relief provided $400 in direct education support for an orphan boy in Bangladesh. The case page now includes local video proof and field photos, while private identity documents are kept off the public website.",
    update: "Case media and field documentation were added on May 13, 2026.",
    thumbnailUrl: "assets/projects/case-003/orphan-education-003-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-003.html",
    donationUrl: "donate.html?program=orphan_annual&amount=300&referrer=case-003#donationForm"
  },
  {
    title: "Feeding Madrasa for Orphan Kids",
    donationLabel: "Feeding Madrasa for Orphan Kids",
    acceptsDonations: true,
    category: "Feeding",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 004",
    amountRaised: "$400",
    verifiedOrphanBeneficiaries: null,
    impact: "Meal service provided for orphan children at a madrasa",
    summary: "Case 004 documents $400 in feeding support for orphan children at a madrasa in Bangladesh. Public photos and video record the meal service on June 24, 2026; no beneficiary count is published.",
    update: "The $400 meal service and proof media were documented on June 24, 2026.",
    thumbnailUrl: "assets/projects/case-004/korbani-meals-004-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-004.html",
    donationUrl: "donate.html?program=orphan_feeding&amount=100&referrer=case-004#donationForm"
  },
  {
    title: "Food Relief for Flood-Affected Families",
    donationLabel: "Flood Relief",
    acceptsDonations: true,
    category: "Flood Relief",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 005",
    amountRaised: "$450",
    impact: "Food supplies delivered to families affected by flooding",
    summary: "One World Relief delivered $450 in food relief to flood-affected families in Bangladesh. The public case page includes field photos and videos from the July 15-16, 2026 response.",
    update: "Field delivery and proof media were documented on July 15-16, 2026.",
    thumbnailUrl: "assets/projects/case-005/flood-relief-005-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-005.html",
    donationUrl: "donate.html?program=emergency_aid&amount=25&referrer=case-005#donationForm"
  },
  {
    title: "A Secure Gate for a Community Mosque",
    donationLabel: "Mosque Gate",
    acceptsDonations: false,
    category: "Mosque Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 006",
    amountRaised: "$170",
    impact: "A secure entrance gate installed for a community mosque",
    summary: "One World Relief supported a $170 secure gate installation for a community mosque in Bangladesh. Photos and videos document the completed work from July 27-31, 2026.",
    update: "Installation and completion proof were documented on July 27-31, 2026.",
    thumbnailUrl: "assets/projects/case-006/mosque-gate-006-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-006.html",
    donationUrl: "donate.html?program=mosque_build&amount=1000&referrer=case-006#donationForm"
  },
  {
    title: "Water for a Madrasa Mosque",
    donationLabel: "Madrasa Water",
    acceptsDonations: true,
    category: "Mosque Support",
    status: "Coming Soon",
    location: "",
    date: "Case 007",
    amountRaised: "Budget coming soon",
    impact: "Water support planned for a madrasa mosque",
    summary: "Case 007 is a planned water project for a madrasa mosque. The location, detailed scope, budget, schedule, and project media will be added when confirmed.",
    update: "Project announced. Planning details are coming soon.",
    thumbnailType: "banner",
    thumbnailLabel: "Coming Soon",
    mediaLabel: "View project",
    mediaUrl: "projects/case-007.html",
    donationUrl: "donate.html?program=water_support&variant=water_station&amount=350&referrer=case-007#donationForm"
  },
  {
    title: "Tiles to Help Finish a Mosque",
    donationLabel: "Mosque Tiles",
    acceptsDonations: true,
    category: "Mosque Support",
    status: "Coming Soon",
    location: "",
    date: "Case 008",
    amountRaised: "Budget coming soon",
    impact: "Tile work planned to help finish a mosque",
    summary: "Case 008 is a planned tile project for a mosque that still needs finishing. The location, detailed scope, budget, schedule, and project media will be added when confirmed.",
    update: "Project announced. Planning details are coming soon.",
    thumbnailType: "banner",
    thumbnailLabel: "Coming Soon",
    mediaLabel: "View project",
    mediaUrl: "projects/case-008.html",
    donationUrl: "donate.html?program=mosque_build&amount=1000&referrer=case-008#donationForm"
  },
  {
    title: "Twenty Ceiling Fans for a New Mosque",
    donationLabel: "Mosque Construction",
    acceptsDonations: false,
    category: "Mosque Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 009",
    amountRaised: "$1,650",
    impact: "20 ceiling fans installed for the mosque’s ground floor",
    summary: "One World Relief has confirmed the completed Case 009 project cost was $1,650. The project installed 20 ceiling fans for the ground floor of a newly built mosque in Bangladesh. Two completion photos are published; donor names, contact information, and the private supporting letter remain off the public website.",
    update: "The installation was documented on September 24, 2025; the completed project cost was later confirmed as $1,650.",
    thumbnailUrl: "assets/projects/case-009/mosque-fans-009-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-009.html",
    donationUrl: "donate.html?program=mosque_build&amount=1000&referrer=case-009#donationForm"
  },
  {
    title: "A Safer Elder-Care Home",
    donationLabel: "Elder Care",
    acceptsDonations: false,
    category: "Elder Care",
    status: "Coming Soon",
    location: "",
    date: "Case 010",
    amountRaised: "Budget coming soon",
    impact: "Renovation support planned for a residential elder-care home",
    summary: "Case 010 is a planned renovation to improve the safety, comfort, and dignity of a residential home serving vulnerable older adults without reliable family support. The location, assessment, repair scope, budget, schedule, and approved project media will be added when confirmed.",
    update: "Project announced. The building assessment and renovation details are coming soon.",
    thumbnailType: "banner",
    thumbnailLabel: "Coming Soon",
    mediaLabel: "View project",
    mediaUrl: "projects/case-010.html",
    donationUrl: "donate.html?program=unrestricted&referrer=case-010#donationForm"
  }
];
