// Author: Fahadbin Alam (fma52), 4/23/26
// Mod by Codex, 4/23/26
// From One World Relief project content board data, 4/23/26
window.ONE_WORLD_RELIEF_PROJECTS = [
  {
    title: "Keeping a Hafiz Student in School",
    category: "Orphan Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 001",
    amountRaised: "$600",
    impact: "Financial support for a young Hafiz student after the loss of his father",
    summary: "One World Relief provided $600 in direct support for a young orphan continuing his Hafiz studies. The case documentation includes field photos and video proof from the delivery.",
    update: "Case media was organized into a donor-facing detail page on May 5, 2026.",
    thumbnailUrl: "assets/projects/case-001/orphan-support-001-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-001.html",
    donationUrl: "donate.html?campaign=Orphan%20Support#donationForm"
  },
  {
    title: "A Fresh Start for a Father's Business",
    category: "Livelihood Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 002",
    amountRaised: "$600",
    impact: "Direct livelihood support for a father rebuilding a small vegetable business",
    summary: "One World Relief provided $600 in financial support so a father of two could restart his vegetable business and support food, education, and daily needs for his family.",
    update: "Case media was organized into a donor-facing detail page on May 10, 2026.",
    thumbnailUrl: "assets/projects/case-002/livelihood-support-002-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-002.html",
    donationUrl: "donate.html?campaign=General%20Fund#donationForm"
  },
  {
    title: "Keeping an Orphan Boy in School",
    category: "Orphan Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 003",
    amountRaised: "$400",
    impact: "Education support delivered for an orphan boy",
    summary: "One World Relief provided $400 in direct education support for an orphan boy in Bangladesh. The case page now includes local video proof and field photos, while private identity documents are kept off the public website.",
    update: "Case media and field documentation were added on May 13, 2026.",
    thumbnailUrl: "assets/projects/case-003/orphan-education-003-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-003.html",
    donationUrl: "donate.html?campaign=Orphan%20Support#donationForm"
  },
  {
    title: "Korbani Meals for a Village",
    category: "Feeding",
    status: "Ongoing",
    location: "Bangladesh",
    date: "Case 004",
    amountRaised: "In progress",
    impact: "Village feeding support being organized for Korbani",
    summary: "Case 004 is an active Korbani feeding case. One World Relief is organizing village meal support, with images and proof media to be added once available.",
    update: "Case opened on May 10, 2026. Media and delivery proof are pending.",
    thumbnailType: "banner",
    mediaLabel: "View case",
    mediaUrl: "projects/case-004.html",
    donationUrl: "donate.html?campaign=Feeding#donationForm"
  },
  {
    title: "Food Relief for Flood-Affected Families",
    category: "Flood Relief",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 005",
    amountRaised: "$450",
    impact: "Food supplies delivered to families affected by flooding",
    summary: "One World Relief delivered $450 in food relief to flood-affected families in Bangladesh. The public case page includes field photos and videos from the July 15-16, 2026 response.",
    update: "Field delivery and proof media were documented on July 15-16, 2026.",
    thumbnailUrl: "assets/projects/case-005/flood-relief-005-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-005.html",
    donationUrl: "donate.html?campaign=General%20Fund#donationForm"
  },
  {
    title: "A Secure Gate for a Community Mosque",
    category: "Mosque Support",
    status: "Completed",
    location: "Bangladesh",
    date: "Case 006",
    amountRaised: "$170",
    impact: "A secure entrance gate installed for a community mosque",
    summary: "One World Relief supported a $170 secure gate installation for a community mosque in Bangladesh. Photos and videos document the completed work from July 27-31, 2026.",
    update: "Installation and completion proof were documented on July 27-31, 2026.",
    thumbnailUrl: "assets/projects/case-006/mosque-gate-006-thumbnail.jpg",
    mediaLabel: "View story",
    mediaUrl: "projects/case-006.html",
    donationUrl: "donate.html?campaign=General%20Fund#donationForm"
  },
  {
    title: "Water for a Madrasa Mosque",
    category: "Mosque Support",
    status: "Coming Soon",
    location: "",
    date: "Case 007",
    amountRaised: "Budget coming soon",
    impact: "Water support planned for a madrasa mosque",
    summary: "Case 007 is a planned water project for a madrasa mosque. The location, detailed scope, budget, schedule, and project media will be added when confirmed.",
    update: "Project announced. Planning details are coming soon.",
    thumbnailType: "banner",
    thumbnailLabel: "Coming Soon",
    mediaLabel: "View project",
    mediaUrl: "projects/case-007.html",
    donationUrl: "donate.html?campaign=General%20Fund#donationForm"
  },
  {
    title: "Tiles to Help Finish a Mosque",
    category: "Mosque Support",
    status: "Coming Soon",
    location: "",
    date: "Case 008",
    amountRaised: "Budget coming soon",
    impact: "Tile work planned to help finish a mosque",
    summary: "Case 008 is a planned tile project for a mosque that still needs finishing. The location, detailed scope, budget, schedule, and project media will be added when confirmed.",
    update: "Project announced. Planning details are coming soon.",
    thumbnailType: "banner",
    thumbnailLabel: "Coming Soon",
    mediaLabel: "View project",
    mediaUrl: "projects/case-008.html",
    donationUrl: "donate.html?campaign=General%20Fund#donationForm"
  }
];
